* gputils/gpasm/cod.c, gputils/gpasm/coff.c:   Changed the comments.
* gputils/gpasm/directive.c, gputils/gpasm/gpasm.h.in:
  Use logical constants.

* gputils/gpasm/gpasm.c:
  Print the new "Idlocs OR Mask" value.

* gputils/gpasm/ppscan.l, gputils/gpasm/preprocess.c:
  Use GP_Strndup() function.

* gputils/gpasm/scan.l:
  Use GP_Strndup() function. Use logical constants.
  Use "IDLOCS CODE" in the --mpasm-compatible mode.
  Thanks to Andrew E. Mileski for the report.

* gputils/gpasm/util.c:
  Code cleaning.

* gputils/gplink/testsuite/gplink.project/hexfiles/reloc12.hex,
  gputils/gplink/testsuite/test:
  Refresh.

* gputils/gplink/cod.c:
  Code cleaning.

* gputils/gplink/gplink.c, gputils/gplink/scan.h, gputils/gplink/script.c:
  Use logical constants.

* gputils/gplink/lst.c, gputils/gplink/map.c:
  Use const modifier.

* gputils/gplink/scan.l:
  Use logical constants.
  Use const modifier.

* gputils/gputils/gpdasm:
  bugfix

* gputils/libgputils/gpcofflink.c, gputils/libgputils/gpprocessor.c:
  Use "IDLOCS CODE" in the --mpasm-compatible mode.

* gputils/libgputils/gpprocessor.h:
  New functions: gp_processor_is_idlocs_byte_addr(),
                   gp_processor_is_config_byte_addr()

* gputils/libgputils/gpsystem.c, gputils/libgputils/gpsystem.h:
  New functions: gp_realloc(), gp_strndup(), GP_Realloc(), GP_Strndup()

* gputils/tools/cmp_gp_mp.sh, gputils/tools/device-help.pl,
  gputils/tools/device-manager.pl:
  Use "IDLOCS CODE" in the --mpasm-compatible mode.

diff --git a/gputils/gplink/testsuite/test b/gputils/gplink/testsuite/test
--- a/gputils/gplink/testsuite/test
+++ b/gputils/gplink/testsuite/test
@@ -25,26 +25,36 @@
 # the future, dejagnu will be used to replace this script.
 
 # Defines
-version=1.1
+version="1.1"
 
 HERE=$(pwd)
 
-TESTDIR=./test
-HEADER=${HERE}/../../header
-LKR=${HERE}/../../lkr
+TESTDIR="./test"
+HEADER="${HERE}/../../header"
+LKR="${HERE}/../../lkr"
 
-GPPATH=${HERE}/../..
-GPASMBIN=${GPPATH}/gpasm/gpasm
+GPPATH="${HERE}/../.."
+GPASMBIN="${GPPATH}/gpasm/gpasm"
 GPASMFLAGS="-q -c"
-GPLIBBIN=${GPPATH}/gputils/gplib
-GPLINKBIN=${GPPATH}/gplink/gplink
+GPLIBBIN="${GPPATH}/gputils/gplib"
+GPLINKBIN="${GPPATH}/gplink/gplink"
 GPLINKFLAGS="-m --strict-options"
 
-MPPATH=/opt/microchip/mplabx/mpasmx
-MPASMBIN=${MPPATH}/mpasmx
+for path in "/opt/microchip/mplabx/"* ; do
+  if test -z "$MPLABX_PATH"; then
+    MPLABX_PATH="$path"
+  fi
+done
+
+if test -z "$MPLABX_PATH"; then
+  MPLABX_PATH="/opt/microchip/mplabx"
+fi
+
+MPPATH="${MPLABX_PATH}/mpasmx"
+MPASMBIN="${MPPATH}/mpasmx"
 MPASMFLAGS="-o"
-MPLIB=${MPPATH}/mplb
-MPLINK=${MPPATH}/mplink
+MPLIB="${MPPATH}/mplib"
+MPLINK="${MPPATH}/mplink"
 MPFLAGS="-m"
 
 # general functions
@@ -63,12 +73,12 @@ binexists()
     return 1
   fi
   echo "testing for $1"
-  if ! test -e $1; then
+  if ! test -e "$1"; then
     echo "$1 not found.  Aborting."
     return 1
   else
-    $1 -v
-    echo "executable found."
+    "$1" -v
+    echo "Executable found."
     echo
     return 0
   fi
@@ -115,11 +125,11 @@ test_gplink_compile()
     do
       # split the base file name from the extension
       basefilename="${x%%.asm}"
-      $GPASMBIN $GPASMFLAGS -I $HEADER $x
-      if test -e $basefilename.o; then
-        echo "$x compiled"
+      "$GPASMBIN" $GPASMFLAGS -I $HEADER "$x"
+      if test -e "$basefilename.o"; then
+        echo "$x compiled."
       else
-        echo "$x failed to compile"
+        echo "$x failed to compile."
         exit 1
       fi
     done
@@ -135,9 +145,9 @@ test_gplink_lib()
 
   echo "archiving $1"
   LIST=*.o
-  $GPLIBBIN -c $1 $LIST
-  if test -e $1; then
-    echo "failed to archive"
+  "$GPLIBBIN" -c "$1" $LIST
+  if test -e "$1"; then
+    echo "Failed to archive."
     exit 1
   fi
 }
@@ -156,18 +166,18 @@ test_gplink_sub()
     return 1
   fi
 
-  if ! test -d $1; then
+  if ! test -d "$1"; then
     echo "$1 not found.  Aborting."
     return 1
   fi
 
   printbanner "Running ./$1 gplink tests"
 
-  cd $1
+  cd "$1"
 
   # create the test directory if it doesn't already exist
-  test -d $TESTDIR || mkdir $TESTDIR || exit 1
-  cd $TESTDIR
+  test -d "$TESTDIR" || mkdir "$TESTDIR" || exit 1
+  cd "$TESTDIR"
   rm -f *
 
   # compile the lib1
@@ -194,21 +204,21 @@ test_gplink_sub()
     do
       # split the base file name from the extension
       basefilename="${x%%.lkr}"
-      if test -e ../hexfiles/$basefilename.hex; then
+      if test -e "../hexfiles/$basefilename.hex"; then
         # a hex file exists so these files must not have errors
         tested=$((tested+1))
         echo "linking $basefilename.o"
         if [ $basefilename == "dead_code" ]; then
           echo "$GPLINKBIN -O2 -o $basefilename.hex $GPLINKFLAGS -I ../../$LKR $basefilename.lkr"
-          $GPLINKBIN -O2 -o $basefilename.hex $GPLINKFLAGS -I $LKR -s $basefilename.lkr
+          "$GPLINKBIN" -O2 -o "$basefilename.hex" $GPLINKFLAGS -I $LKR -s "$basefilename.lkr"
         else
           echo "$GPLINKBIN -o $basefilename.hex $GPLINKFLAGS -I ../../$LKR $basefilename.lkr"
-          $GPLINKBIN -o $basefilename.hex $GPLINKFLAGS -I $LKR -s $basefilename.lkr
+          "$GPLINKBIN" -o "$basefilename.hex" $GPLINKFLAGS -I $LKR -s "$basefilename.lkr"
         fi
-        if test -e $basefilename.hex; then
+        if test -e "$basefilename.hex"; then
           compiled=$((compiled+1))
-          diff -s -u ../hexfiles/$basefilename.hex $basefilename.hex
-          if diff -q ../hexfiles/$basefilename.hex $basefilename.hex; then
+          diff -s -u "../hexfiles/$basefilename.hex" "$basefilename.hex"
+          if diff -q "../hexfiles/$basefilename.hex" "$basefilename.hex"; then
             passed=$((passed+1))
             echo "$basefilename.lkr tested successfully"
           fi
@@ -220,8 +230,8 @@ test_gplink_sub()
         # errors
         errortested=$((errortested+1))
         echo "linking $basefilename.lkr"
-        $GPLINKBIN -o $basefilename.hex $GPLINKFLAGS -I $LKR -s $basefilename.lkr
-        if test -e $basefilename.hex; then
+        "$GPLINKBIN" -o "$basefilename.hex" $GPLINKFLAGS -I $LKR -s "$basefilename.lkr"
+        if test -e "$basefilename.hex"; then
           echo "$basefilename.lkr failed to generate an error"
         else
           notcompiled=$((notcompiled+1))
